//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegisterApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int StudentID { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Class is required")]
        public string Class { get; set; }

        [Required(ErrorMessage = "Roll is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Roll must be a positive number")]
        public int Roll { get; set; }

        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Country is required")]
        public Nullable<int> CountryID { get; set; }

        [Required(ErrorMessage = "State is required")]
        public Nullable<int> StateID { get; set; }

        [Required(ErrorMessage = "City is required")]
        public Nullable<int> CityID { get; set; }

        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }

        public virtual City City1 { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual State State1 { get; set; }
    }
}
